name: Staging Phase

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout Repository
      uses: actions/checkout@v2
    -
      name: Clear .env to make program use env from container
      run: echo "" > .env
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mebanten:customer-be-dev-${{ github.sha }},${{ secrets.DOCKER_HUB_USERNAME }}/mebanten:customer-be-dev-latest
    - 
      name: Executing remote command using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd deploy-mebanten/dev
          docker compose rm -sf customer-be
          docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/mebanten:customer-be-dev-latest
          docker compose up -d customer-be
